version: '2'

services:
  monero-rpc:
    build: .
      # context: .
      # dockerfile: Dockerfile
      # args:
        #BRANCH: v0.12.3.0
        # v0.12.3.0: /monero/build/release/bin
        # v0.13.0.1-RC1 /monero/build/Linux/_no_branch_/release/bin
        # master:    /monero/build/Linux/master/release/bin
        #BUILD_PATH: /monero/build/Linux/master/release/bin
    command: monero-wallet-rpc --testnet --wallet-file wallet --password-file wallet.passwd --disable-rpc-login
    volumes:
      - <path_to_contents_of_wallet_folder>:/monero
    ports:
      - "28083:28083"
    environment:
      - USER_ID=1000
      - LOG_LEVEL=0
      - DAEMON_HOST=<host>
      - DAEMON_PORT=28081
      - RPC_BIND_IP=0.0.0.0
      - RPC_BIND_PORT=28083
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    restart: unless-stopped
