version: '2'

services:
  monero-rpc:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: 1000
    command: monero-wallet-rpc --testnet --daemon-host <host> --wallet-file wallet --password-file wallet.passwd --disable-rpc-login
    volumes:
      - <path_to_contents_of_wallet_folder>:/monero
    ports:
      - "28083:28083"
    environment:
      - LOG_LEVEL=0
      - RPC_BIND_IP=0.0.0.0
      - RPC_BIND_PORT=28083
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    restart: unless-stopped
