version: '2'

services:
  tritond-testnet:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BRANCH: master
    command: --testnet --data-dir /triton --non-interactive
    volumes:
      # /monero in container should eventually contain the contents of the folder .bitmonero
      - <path/to/and/including/.triton>:/triton
    ports:
      - "9230:9230"
      - "9231:9231"
    environment:
      - USER_ID=1000
      - P2P_BIND_IP=0.0.0.0
      - P2P_BIND_PORT=9230
      - LOG_LEVEL=0
      - RPC_USER=""
      - RPC_PASSWD=""
      - RPC_BIND_IP=0.0.0.0
      - RPC_BIND_PORT=9231
      - USE_TORSOCKS=NO
      - USE_TOR=NO
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
