version: '2'

services:
  monero-rpc:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: 1000
    command: monero-wallet-rpc --stagenet --daemon-host node.xmr.to --wallet-file test --password-file test.passwd --disable-rpc-login
    volumes:
      - ~/Monero/wallets/test:/monero
    ports:
      - "28083:28083"
    environment:
      - LOG_LEVEL=0
      - RPC_BIND_IP=0.0.0.0
      - RPC_BIND_PORT=18083
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    restart: unless-stopped
